### ISSUE TITLE
Using react-dot-fragment causes re-renders

### ISSUE THREAD

**Issue by sandeepdreddy** [benwiley4000/react-dot-fragment#6]
Using this package causes re-renders and as a result input fields lose focus
- Codepen with issue: https://codepen.io/anon/pen/BbYMYj
- Codepen using `React.Fragment`: https://codepen.io/anon/pen/WmMPBO

**Comment by benwiley4000** [comment]
@sandeepdreddy thanks for the repro case! I think I fixed this in react-dot-fragment version 0.2.9. Could you try it?

**Comment by benwiley4000** [comment]
To be clear, re-renders (as you're referring to them) are unavoidable. We're not actually replacing the dom elements themselves but we are moving elements around to convince React nothing changed.

I think the solution to your problem, though, is to just hold a reference to the previously focused element and restore focus when the render is finished: https://github.com/benwiley4000/react-dot-fragment/commit/7180abc1819530be3313ca43b722478b01c333d7

Does that seem ok? Or do you still have other problems?

**Comment by benwiley4000** [comment]
here's a codepen with the new dependency version: https://codepen.io/anon/pen/drjJvy

**Comment by benwiley4000** [comment]
I'll close the issue for now. Let me know if you think there's still an issue and we can re-open it.
